name: DEV DEPLOYMENT

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on:
      - self-hosted
      - dev
    steps:
      - name: reset repo to HEAD and git pull
        working-directory: ${{ secrets.DEV_DEPLOY_PATH }}
        run: git checkout dev && git reset --hard && git pull
      - name: Build dashboard in production
        working-directory: ${{ secrets.DEV_DEPLOY_PATH }}
        run: NODE_ENV=production yarn build
      - name: import latest config sync
        working-directory: ${{ secrets.DEV_DEPLOY_PATH }}
        run: yarn cs import --yes
      - name: restart service
        working-directory: ${{ secrets.DEV_DEPLOY_PATH }}
        run: pm2 restart server
