name: PROD DEPLOYMENT

on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on:
      - self-hosted
      - prod
    steps:
      - name: reset repo to HEAD and git pull
        working-directory: ${{ secrets.PROD_DEPLOY_PATH }}
        run: git checkout prod && git reset --hard && git pull
      - name: Build dashboard in production
        working-directory: ${{ secrets.PROD_DEPLOY_PATH }}
        run: NODE_ENV=production yarn build
      - name: import latest config sync
        working-directory: ${{ secrets.PROD_DEPLOY_PATH }}
        run: yarn cs import --yes
      - name: restart service
        run: sudo pm2 restart server
